//User Type
export const REQUEST_USER_LOGIN = 'user/REQUEST_USER_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'user/REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'user/REQUEST_LOGIN_FAILURE';
export const REQUEST_ADMIN_LOGOUT = 'user/REQUEST_ADMIN_LOGOUT';
export const REQUEST_ADMIN_DETAILS = 'user/REQUEST_ADMIN_DETAILS';
export const RECEIVE_ADMIN_DETAILS = 'user/RECEIVE_ADMIN_DETAILS';
export const REQUEST_RESET_PASSWORD = 'user/REQUEST_RESET_PASSWORD';
export const SUCCESS_RESET_PASSWORD = 'user/SUCCESS_RESET_PASSWORD';
export const FAILURE_RESET_PASSWORD = 'user/FAILURE_RESET_PASSWORD';
export const REFRESH_TOKEN = "user/REFRESH_TOKEN";
