export const REQUEST_STRATEGY_ADD = "strategy/REQUEST_STRATEGY_ADD";
export const REQUEST_UPDATE_STRATEGY = "strategy/REQUEST_UPDATE_STRATEGY";
export const REQUEST_STRATEGY_SINGLE = "strategy/REQUEST_STRATEGY_SINGLE";
export const REQUEST_STRATEGY_LIST = "strategy/REQUEST_STRATEGY_LIST";
