export const REQUEST_CONCEPT_ADD = "concept/REQUEST_CONCEPT_ADD";
export const REQUEST_CONCEPT_LIST = "concept/REQUEST_QUESTIONS_LIST";
export const REQUEST_UPDATE_CONCEPT = "concept/REQUEST_UPDATE_QUESTIONS";
export const REQUEST_DELETE_CONCEPT = "concept/REQUEST_DELETE_QUESTIONS";
export const REQUEST_QUESTION_SUCCESS = "concept/REQUEST_QUESTION_SUCCESS";
export const REQUEST_ANSWERS_SUCCESS = "concept/REQUEST_ANSWERS_SUCCESS";
export const REQUEST_QUESTIONS_LISTSUCCESS =
  "concept/REQUEST_QUESTIONS_LISTSUCCESS";
