export const REQUEST_CHAPTER_ADD = "chapter/REQUEST_CHAPTER_ADD";
export const REQUEST_UPDATE_CHAPTER = "chapter/REQUEST_UPDATE_CHAPTER";
export const REQUEST_CATEGORY_LIST = "chapter/REQUEST_CATEGORY_LIST";
export const REQUEST_CHAPTER_LIST = "chapter/REQUEST_CHAPTER_LIST";
