export const REQUEST_QUESTIONS_ADD = "question/REQUEST_QUESTIONS_ADD";
export const REQUEST_ANSWERS_ADD = "question/REQUEST_ANSWERS_ADD";
export const REQUEST_QUESTIONS_LIST = "question/REQUEST_QUESTIONS_LIST";
export const REQUEST_ANSWER_LIST = "question/REQUEST_ANSWER_LIST";
export const REQUEST_UPDATE_QUESTIONS = "question/REQUEST_UPDATE_QUESTIONS";
export const REQUEST_UPDATE_ANSWER = "question/REQUEST_UPDATE_ANSWER";
export const REQUEST_DELETE_QUESTIONS = "question/REQUEST_DELETE_QUESTIONS";
export const REQUEST_DELETE_ANSWERS = "question/REQUEST_DELETE_ANSWERS";

export const REQUEST_QUESTION_SUCCESS = "question/REQUEST_QUESTION_SUCCESS";
export const REQUEST_ANSWERS_SUCCESS = "question/REQUEST_ANSWERS_SUCCESS";
export const REQUEST_QUESTIONS_LISTSUCCESS =
  "question/REQUEST_QUESTIONS_LISTSUCCESS";
